### PR TITLE
Follow the new styleguide of djangoproject.com

### PR DESCRIPTION
**Pull request by relekang**
This should follow the new styleguide, at least in best efforts. I chose to use sass and a makefile since that is what is used in the djangoproject.com-project. Below is a screenshot from my local version.

screenshot 2015-01-13 20 28 53

### CODE REVIEW

**Comment by jezdez** [comment]
Huh, that makes me wonder if we should move that code over to the main repo, now that we have a way to properly host multiple hosts under one Django project using django-hosts. What do you think? @aaugustin? I think it would make sense to cut down the number of sites we have to maintain, don't you think?

**Comment by aaugustin** [comment]
The dev dashbord lives just fine as a separate app.

Only if there are tangible benefits in terms of CSS factorization would I merge it with the website.

**Comment by jezdez** [comment]
The future cost of maintenance in this repo for styles outweigh the one time effort to move things over to the website repo.

I think it's also fair to say that we have a lot more interest in keeping our eggs in one basket so to say, than having to go through a list of projects whenever we update Django or a dependency. I agree that this may be unrelated but now that we actual have a working group for the website we should consider using it.

**Comment by relekang** [comment]
Sounds good to me. I'll be happy to help if you decide to move things over to the djangoproject.com repo.

**Comment by aaugustin** [comment]
That counts as tangible benefits, go ahead.

**Comment by relekang** [comment]
I'm closing this and opening one on the djangoproject repo instead.

**Pull request closed without merging**
